
theme: jekyll-theme-cayman
title: typed2
description: Type-safe keys for obnoxious key-value stores.
version: 2.0.0-SNAPSHOT
docsDir: https://episode6.github.io/typed2/docs/main
kotlinVersion: 1.7.10
