#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ ! -f "$SCRIPT_DIR/launch_docs_site.sh" ]; then
    SCRIPT_DIR=${0:a:h}
fi

cd $SCRIPT_DIR
./gradlew configSite

cp build/site/_config.yml docs/

cd $SCRIPT_DIR/docs
bundle exec jekyll serve
