# Minorly adjusted from https://gist.github.com/badsyntax/ce848ab40b952d944c496575d40e5427 and https://github.com/igorboskovic3/actions-test/actions/runs/3239143575/workflow

name: Sample App connectedCheck

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  sample-app-connected-check:
    runs-on: macos-12
    strategy:
      matrix:
        api-level: [21]
    timeout-minutes: 45 # No default
    env:
      JAVA_TOOL_OPTIONS: -Xmx4g
      GITHUB_WORKSPACE: ${{ github.workspace }}
      GITHUB_RUN_NUMBER: ${{ github.run_number }}
      HOMEBREW_NO_INSTALL_CLEANUP: 1

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Install Haxm
        run: brew install --cask intel-haxm

      - name: install ffmpeg session
        run: brew install ffmpeg

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: record session
        run: |
          ffmpeg -f avfoundation -i 0 -t 120 out.mov &

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -partition-size 2048 -qemu -m 2048
          disable-animations: true
          script: |
            # Take Screenshot of VM to verify emulator start
            screencapture screenshot.jpg
            # Take picture of emulator to verify emulator start
            $ANDROID_HOME/platform-tools/adb exec-out screencap -p > emulator.png
            ./gradlew :sample-app:connectedCheck

      - name: upload video
        uses: actions/upload-artifact@master
        with:
          name: out
          path: out.mov

      - uses: actions/upload-artifact@v3
        with:
          name: screenshot.jpg
          path: screenshot.jpg

      - uses: actions/upload-artifact@v3
        with:
          name: emulator.png
          path: emulator.png
